### ISSUE TITLE
poly_surface.scad - Surface is not axisymmetric

### ISSUE THREAD

**Issue by ytakeyasu** [KitWallace/openscad#6]
It seems surface is not axisymmetric.
Replacing the original "nx" and "ny" with "nx+1" and "ny+1" respectively work for me.

**Comment by KitWallace** [comment]
Thanks for your  observation

do you mean
module poly_surface (minx,maxx,miny,maxy,nx,ny) {
// uses ftop() and fbottom()  to computer surface heights 
   nx=nx+1;
   ny=ny+1;
   sv=surface_vertices(minx,maxx,miny,maxy,nx,ny);   
   // echo("vertices",sv);
   sf=surface_faces(nx,ny);     
   // echo("faces",sf);    
   polyhedron(sv,sf);
};

**Comment by ytakeyasu** [comment]
Sorry for making you confused...
I mean:
// vertex indexes
function vt(i,j,nx,ny) = i*(nx+1) + j;
function vb(i,j,nx,ny) = (nx+1)*(ny+1) +i * (nx+1) + j;
  
function surface_vertices (minx,maxx,miny,maxy,nx,ny) = 
// vertices 
    concat(
     flatten([for (i=[0:nx])
        let (x= minx + (maxx-minx)*i/nx)
        [for (j=[0:ny])
            let (y= miny + (maxy-miny)*j/ny)
            [x,y,ftop(x,y)]
        ]
    ]),
    flatten([for (i=[0:nx])
       let (x= minx + (maxx-minx)*i/nx)
       [for (j=[0:ny])
           let (y= miny + (maxy-miny)*j/ny)
           [x,y,fbottom(x,y)]
        ]
    ])
    );
        
function surface_faces (nx,ny) = 
  concat(
    flatten(
      [for (i=[0:nx-1])
        [for (j=[0:ny-1])
           reverse(
            [vt(i,j,nx,nx),
            vt(i+1,j,nx,nx),
            vt(i+1,j+1,nx,nx),
            vt(i,j+1,nx,nx)]
           )
        ]
     ]),
    flatten(
      [for (i=[0:nx-1])
         [for (j=[0:ny-1])
             [vb(i,j,nx,nx),
              vb(i+1,j,nx,nx),
              vb(i+1,j+1,nx,nx),
              vb(i,j+1,nx,nx)
             ]
         ]
       ]),
    [for (i=[0:nx-1])
           [vt(i,0,nx,nx),
            vt(i+1,0,nx,nx),
            vb(i+1,0,,nx,nx),
            vb(i,0,,nx,nx)
           ]
    ],
    [for (i=[0:nx-1])
        reverse(
           [vt(i,ny,nx,nx),
            vt(i+1,ny,nx,nx),
            vb(i+1,ny,nx,nx),
            vb(i,ny,nx,nx)
           ])
    ],
    [for (j=[0:ny-1])
       reverse(
         [vt(0,j,nx,nx),
         vt(0,j+1,nx,nx),
         vb(0,j+1,nx,nx),
         vb(0,j,nx,nx)])
    ],
     [for (j=[0:ny-1])
        [vt(nx,j,nx,nx),
         vt(nx,j+1,nx,nx),
         vb(nx,j+1,nx,nx),
         vb(nx,j,nx,nx)]
       ]   
    );

**Comment by KitWallace** [comment]
No I'm sorry  - -  code is 7 years old and I forget what Ive done sometimes!

Thanks for the improvement - implemented

**Comment by ytakeyasu** [comment]
Thanks for your prompt implementation. The latest issue notification reminds me this issue this morning, though I found this issue 7 years ago too. I used this code to generate surface models for Electro-Magnetic Simulation, because both codes mathematically go well together as you originally intended. Thanks again for your great open source codes.
